### ISSUE TITLE
Issue with peer dependency for `typescript-eslint`

### ISSUE THREAD

**Issue by acommodari** [sweepline/eslint-plugin-unused-imports#99] opened 2024-08-20 20:14 UTC
I am getting peer dependency issues when I try to use this package with the new `typescript-eslint` v8 because the package is expecting the old `@typescript-eslint/eslint-plugin` package

**Comment by antfu** [comment] 2024-08-20 20:23
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-20 20:23 UTC
