### ISSUE TITLE
Definition for rule 'unused-imports/no-unused-imports' was not found

### ISSUE THREAD

**Issue by sang4lv** [sweepline/eslint-plugin-unused-imports#96] opened 2024-08-09 03:35 UTC
I'm using VSCode with ESlint extension version 3.0.10 with the following dependencies installed in the project

```shell
@typescript-eslint/eslint-plugin 7.18.0
@typescript-eslint/parser 7.18.0
eslint 8.57.0
eslint-config-next 14.2.3
eslint-config-prettier 9.1.0
eslint-plugin-prettier 5.2.1
eslint-plugin-react 7.35.0
eslint-plugin-unused-imports 4.1.2
```

Once ESlint server started locally, it would report the following errors for every file that I open:

```shell
Definition for rule 'unused-imports/no-unused-imports' was not found.eslint(unused-imports/no-unused-imports)
Definition for rule 'unused-imports/no-unused-vars' was not found.eslint(unused-imports/no-unused-vars)
```

I noticed that other projects with 4.0.1 version of `eslint-plugin-unused-imports` didn't have this problem.

**Comment by antfu** [comment] 2024-08-09 04:08
Looks like it duplicates https://github.com/sweepline/eslint-plugin-unused-imports/issues/94, otherwise, please provide a minimal reproduction

**Comment by antfu** [comment] 2024-08-09 04:08
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-09 04:08 UTC
