### ISSUE TITLE
Remove unused imports not happening on save

### ISSUE THREAD

**Issue by DanPatten** [sweepline/eslint-plugin-unused-imports#97] opened 2024-08-16 16:21 UTC
My eslint config:

`

        "no-unused-vars": "off", // no-unused-imports handles this
        "@typescript-eslint/no-unused-vars": "off", // no-unused-imports handles this
        "@typescript-eslint/no-unused-imports": "off", // no-unused-imports handles this
        "unused-imports/no-unused-imports": "error",
        "unused-imports/no-unused-vars": [
            "error",
            {
                vars: "all",
                varsIgnorePattern: "^_",
                args: "after-used",
                argsIgnorePattern: "^_",
                ignoreRestSiblings: true,
            },
        ],
`

Now in my app.code-workspace in VS Code I have this set

`   "editor.codeActionsOnSave": {
              "source.fixAll.eslint": "explicit"
          },`
          
However this plugin does not remove unused imports on save. If I run eslint fix on the file it works fine.

**Comment by antfu** [comment] 2024-08-17 12:24
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed** 2024-08-19 08:57 UTC
