### ISSUE TITLE
Issue when linting UI library

### ISSUE THREAD

**Issue by skitscha** [sweepline/eslint-plugin-unused-imports#86] opened 2024-07-12 19:11 UTC
I'm trying to run the linter on a UI library. However, this plugin seems to blowup when its gets to a specific component each time. It is giving me the error:
TypeError: Cannot destructure property 'parent' of 'node' as it is undefined.

Rule: "unused-imports/no-unused-imports"

It seems to be blowing up on this line of code:
![image](https://github.com/user-attachments/assets/b9b5a11f-0852-4e06-b6ef-0681aac9d965)

Do you have any ideas on what could be causing this?

**Comment by Samuel-Therrien-Beslogic** [comment] 2024-07-15 18:19
What's your `eslint-plugin-unused-imports` and `@typescript-eslint/eslint-plugin` versions ?
I had the same issue and it was fixed by updating `eslint-plugin-unused-imports@3.2.0`. See https://github.com/sweepline/eslint-plugin-unused-imports/issues/77

**Comment by antfu** [comment] 2024-08-09 03:32
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-09 03:32 UTC
