### ISSUE TITLE
TypeError when using ESLint v9 with v4.x.x

### ISSUE THREAD

**Issue by ruiaraujo012** [sweepline/eslint-plugin-unused-imports#91] opened 2024-08-05 10:02 UTC
I was receiving some of these errors:

```
TypeError: context.getScope is not a function
TypeError: context.getAncestors is not a function
TypeError: context.markVariableAsUsed is not a function
TypeError: context.getDeclaredVariables is not a function
```
 I had to do the following to remove them.
```js
plugins: {
      'unused-imports': fixupPluginRules(unusedImports),
},
```

Could you take a look and see if there's something missing in v4.x.x?

---
https://eslint.org/docs/latest/use/troubleshooting/v9-rule-api-changes

**Comment by antfu** [comment] 2024-08-08 17:17
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-08 17:17 UTC

**Comment by SamuelTrew** [comment] 2024-10-04 14:50
This may help those who face this issue.
I believe it's due to @typescript-eslint/eslint-plugin and @typescript-eslint/parser being out of date.

They need to be on 8.x.y I believe for this plugin to work on version 4.a.b
